/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 motorcycle.glb --transform --keepmeshes --keepmaterials --format --shadows 
Files: motorcycle.glb [339.37MB] > C:\Users\user\Desktop\motorcycle-transformed.glb [12.45MB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MotorModel(props) {
  const { nodes, materials } = useGLTF('/motorcycle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -0.998]} scale={[0.032, 0.111, 0.111]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane012.geometry} material={materials.shiny_blackbolt} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_1.geometry} material={materials.front_shock} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_2.geometry} material={materials.tire} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_3.geometry} material={materials.brake_plae} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_4.geometry} material={materials.rustymetal} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_5.geometry} material={materials.rim} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_6.geometry} material={materials.semiblack} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_7.geometry} material={materials.silver} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_8.geometry} material={materials.screw} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_9.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_10.geometry} material={materials.caliper} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_11.geometry} material={materials.rubber} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_12.geometry} material={materials['galva iron']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_13.geometry} material={materials.shiny_darkgreen} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_14.geometry} material={materials.shiny_yellow_metal} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_15.geometry} material={materials.white_plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_16.geometry} material={materials.white} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_17.geometry} material={materials.rustty_black} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_18.geometry} material={materials.glass} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_19.geometry} material={materials.mirror} />
        <mesh castShadow receiveShadow geometry={nodes.Plane012_20.geometry} material={materials.dark_blue} />
      </group>
    </group>
  )
}

useGLTF.preload('/motorcycle-transformed.glb')
